apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ink-rules
  labels:
    namespace: ink
    component: ink-ingress
  namespace: ink
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/websocket-services: "server-svc"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  tls:
  - hosts:
    - staging.ink-remix.blockchain-it.hr
    secretName: staging.ink-remix-secret
  rules:
  - host: server.staging.ink-remix.blockchain-it.hr  
    http:
      paths:
      - backend:
          serviceName: server-svc
          servicePort: 80
  - host: plugin.staging.ink-remix.blockchain-it.hr  
    http:
      paths:
      - backend:
          serviceName: plugin-svc
          servicePort: 80   
